# Deploy for Cloudia
# Documentation related to actions used: https://github.com/despegar/actions

name: '[Not Runnable] - Cloudia - Deploy Template'
run-name: Execute Deploy

on:
  workflow_dispatch:
    inputs:
      hola:
        required: true
        type: string

jobs:
  deploy:
    name: Execute deploy
    runs-on: [ self-hosted ]
    continue-on-error: false
    steps:

      - name: Link Actions
        run: echo test

      - name: Test tag
        run: |
          git tag -a "0.0.0" -m "Version: 0.0.0"
          git push && git push origin "0.0.0"
